### ISSUE TITLE
comparison with 'barrelsby'

### ISSUE THREAD

**Issue by chase-moskal** [mscolnick/export-typescript#1]
hello, i noticed this project in my github feed, and it reminded me of a tool i'm already familiar with called [`barrelsby`](https://www.npmjs.com/package/barrelsby)

at first glance, i assume this tool performs a similar task, and i was just wondering what differences there might be between the two projects

**Comment by mscolnick** [comment]
It looks very similar. `export-typescript` allows for both

```ts
export * from "./DropDown";
export * from "./TextBox";
```
or the more granular version
```ts
export {DropDown, DropDownProps} from "./DropDown";
export {TextBox, TextBoxProps} from "./TextBox";
```

This is also a built-in vscode extension that works with the command palette
