### ISSUE TITLE
Bug : export-typescript.replace-exports not found

### ISSUE THREAD

**Issue by sk-izsk** [mscolnick/export-typescript#15]
**Describe the bug**

when we run the extension that is `Export Typescript: Write exports` it throws this error : `export-typescript.replace-exports` . Kindly see the picture.  I try to reinstall the extension so far no luck

**To Reproduce**
1. Go to 'command pallete and run: Export Typescript: Write exports '
2. See error in the pic

**Expected behavior**
I should exports normally

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac os Bigsur 11.4 , windows 10

**Additional context**
Version of extension : 0.4.0

Thanks

![Screen Shot 2021-08-04 at 3 46 45 PM](https://user-images.githubusercontent.com/35744979/128245236-1cc3b00f-264d-4dfa-b959-5f68fa86bbc8.png)

**Comment by mscolnick** [comment]
@sk-izsk I just published `0.4.1` with fix. Can you try that out and let me know if you are still experiencing issues?

**Comment by sk-izsk** [comment]
> @sk-izsk I just published `0.4.1` with fix. Can you try that out and let me know if you are still experiencing issues?

Hi , thanks for reply, I test this good thing is I dont get any error now but when I run the command in index.ts file it completely delete every import of that file and become empty index.ts file, these are my config

```json
 "export-typescript.excludes": ["*.{spec.ts,spec.tsx}"],
  "export-typescript.includes": [
    "*.{ts,tsx,js,jsx,vue}",
    "*/index.{ts,tsx,js,jsx,vue}"
  ],
  "export-typescript.exportStar": true,
```

**Comment by sk-izsk** [comment]
One more update : In mac os it behave normally, for windows 10 it still having issue. Thanks

**Comment by mscolnick** [comment]
Yea it is definitely possible that is does not work on windows as I have not tested it out. Do you want to try making a fix? I don't have a windows computer to test

**Comment by sk-izsk** [comment]
> Yea it is definitely possible that is does not work on windows as I have not tested it out. Do you want to try making a fix? I don't have a windows computer to test

Hey, its seems like it works on Windows 10 as well. I am running windows 10 with wsl 1 . I restart the wsl and it seems like working fine, Thanks for the fix. I use your extension on daily basis and can't thank you enough for how much it saves my time in the office.

**Comment by artfulsage** [comment]
@mscolnick hey! I'm getting the same error now while trying to debug the extension. My working branch is up-to-date (0.4.1).
Mac OS Big Sur 11.4
VSCode 1.59.1

**Comment by artfulsage** [comment]
@mscolnick I fixed the error by adding again "typescript-parser" into the external section of rollup config.
