### ISSUE TITLE
Install and subsequent run doesn't work

### ISSUE THREAD

**Issue by Javaman2** [mscolnick/export-typescript#7]
**Describe the bug**

**To Reproduce**
1. Install this tool from Visual Studio Extensions
2. Move to a folder with lots of ts files
3. Create an index.ts in that folder, right click select Command Palette.
4. Go to View/command Palette
4. Pick Export Typescript : Write Exports

Note nothing happens at this point.

**Expected behavior**
Should see all the exports pop up.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Pro
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 85

 

**Additional context**

**Comment by mscolnick** [comment]
This should be fixed on latest. Let me know if its broken for you still
