### ISSUE TITLE
Double quotes and lint

### ISSUE THREAD

**Issue by deandreamatias** [mscolnick/export-typescript#8]
In some projects, the ESLint is setting to enable warning when use double quotes, but by default export-typescript extension, create file with double quotes and I need fix this warnings.

Propose:
Option 1 (recommended): Create a setting value in extension to enable/disable double quotes
Option 2: Replace in [this line](https://github.com/mscolnick/export-typescript/blob/2a385b86bd581305a738b2c6b194f745ea517f4a/src/replace-exports.ts#L91) double quotes for single quotes.

PS: Thanks for this helpful extension 💙

**Comment by mscolnick** [comment]
hey, Option 1 sounds good to me. happy to review if you can put up the PR.

fwiw, i also use single quotes, but i use the `prettier` that will auto-format on save, so it will fix the double quotes as well as fit to desired line-length

**Comment by deandreamatias** [comment]
I never develop any extension, but can try.
I believe than add in [this file](https://github.com/mscolnick/export-typescript/blob/2a385b86bd581305a738b2c6b194f745ea517f4a/src/config.ts#L13) the config and create logic to verify setting in [this line](this line), can work.
Is correct?

**Comment by mscolnick** [comment]
I think to keep the complexity / conditional-configuration low, lets just let `prettier` do this or the user's preferred formatter. Going to close this

**Comment by artfulsage** [comment]
@mscolnick can you reopen this issue please? I can make a PR with required changes. We don't use Prettier.

**Comment by mscolnick** [comment]
@artfulsage of course. feel free to make the PR and I can review.

**Comment by mscolnick** [comment]
This has been release `0.4.2`
