### ISSUE TITLE
Extension not work after update to v0.3.2

### ISSUE THREAD

**Issue by SwerBillionaire** [mscolnick/export-typescript#9]
**Describe the bug**
using command to write export is doing nothing after I updated extension to v0.3.2

**To Reproduce**
1. cmd + shift + P<open command palette>
2. type Export Typescript: Write exports
3. enter
4. If index.ts has exports, it will be replaced with a blank line. If create new index.ts file, nothing happens

**Expected behavior**
export as it is

**Desktop (please complete the following information):**
 - OS: macOS BigSur 11.1
 - Version VSCode 1.52.1

**Additional context**
Use v0.3.1 is working well

**Comment by mtleonard120** [comment]
I had not used this extension in some time and I am also seeing this behavior in 0.3.2, though I had to revert all the way back to version 0.0.5 for it to work again for me.

**Comment by roxfives** [comment]
If it helps anyone, setting the default configs manually in the settings file made the extension work for me.

**Comment by mscolnick** [comment]
This should be fixed on latest `0.4.1`. There was a [typo here](https://github.com/mscolnick/export-typescript/commit/e69d74d2fa7b8492fd2a2feeaa3b1ec28268a840#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L61).
